In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [ ]:
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.ensemble import RandomForestClassifier

In [ ]:
import pandas_profiling as pp

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/machine_learning/ML_project/stroke/healthcare-dataset-stroke-data.csv')

In [ ]:
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
#pp.ProfileReport(df) 

In [ ]:
df1=df.copy(deep=True)
df1

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [ ]:
df1.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [ ]:
data=df1.drop(df[['id']],axis=1)

In [ ]:
data['bmi'].fillna(data['bmi'].median(),inplace=True)

In [ ]:
data['bmi'].dropna(inplace=True)

In [ ]:
gender={'Female':0,'Male':1,'Other':2}
data['gender']=data['gender'].map(gender)

smoking_status={'never smoked':0,'Unknown':1,'formerly smoked':2,'smokes':3}
data['smoking_status']=data['smoking_status'].map(smoking_status)

work_type={'Private':0,'Self-employed':1,'children':2,'Govt_job':3,'Never_worked':4}
data['work_type']=data['work_type'].map(work_type)

Residence_type={'Urban':0,'Rural':1}
data['Residence_type']=data['Residence_type'].map(Residence_type)

ever_married={'Yes':0,'No':1}
data['ever_married']=data['ever_married'].map(ever_married)

In [ ]:
X=data.drop('stroke',axis=1)
y=data['stroke']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=40)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
std=StandardScaler().fit(X_train)

In [ ]:
X_train_std=std.transform(X_train)
X_test_std=std.transform(X_test)

In [ ]:
X_train=X_train_std
X_test=X_test_std

In [ ]:
rfc=RandomForestClassifier()

In [ ]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
predict_train = rfc.predict(X_train)
print('\nTarget on train data',predict_train)


Target on train data [0 0 0 ... 0 0 0]


In [ ]:
predict_test = rfc.predict(X_test)
print('\nTarget on test data',predict_test)


Target on test data [0 0 0 ... 0 0 0]


In [ ]:
accuracy_train = accuracy_score(y_train,predict_train)
print('\naccuracy_score on train dataset : ', accuracy_train)


accuracy_score on train dataset :  1.0


In [ ]:
accuracy_test = accuracy_score(y_test,predict_test)
print('\naccuracy_score on test dataset : ', accuracy_test)


accuracy_score on test dataset :  0.9530516431924883


In [ ]:
rfc_cr=(metrics.classification_report(y_test,predict_test))
print(rfc_cr)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1220
           1       0.25      0.02      0.03        58

    accuracy                           0.95      1278
   macro avg       0.60      0.51      0.50      1278
weighted avg       0.92      0.95      0.93      1278



In [ ]:
rcf_cm=confusion_matrix(y_test,predict_test)
rcf_cm

array([[1217,    3],
       [  57,    1]])

In [ ]:
n_estimators = [100,140,145,150,160, 170,175,180,200];
cv = StratifiedKFold(n_splits=10,random_state=42,shuffle=True)

In [ ]:
parameters = {'n_estimators':n_estimators,
              'criterion':['gini','entropy'],
              'max_features':['log2','sqrt'],
              'random_state':[42,12,100,200,35]
              
        }

In [ ]:
grid = GridSearchCV(estimator=rfc,param_grid=parameters,
                                 cv=cv,
                                 n_jobs = -1)

In [ ]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=42, shuffle=True),
             estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['log2', 'sqrt'],
                         'n_estimators': [100, 140, 145, 150, 160, 170, 175,
                                          180, 200],
                         'random_state': [42, 12, 100, 200, 35]})

In [135]:
print (grid.best_score_)
print (grid.best_params_)
print (grid.best_estimator_)

0.9485918461705831
{'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 200, 'random_state': 12}
RandomForestClassifier(max_features='log2', n_estimators=200, random_state=12)


In [136]:
rfc_cv=RandomForestClassifier(max_features='log2', n_estimators=200, random_state=12)

In [137]:
rfc_cv.fit(X_train,y_train)

RandomForestClassifier(max_features='log2', n_estimators=200, random_state=12)

In [138]:
predict_train = rfc_cv.predict(X_train)
print('\nTarget on train data',predict_train)


Target on train data [0 0 0 ... 0 0 0]


In [139]:
predict_test = rfc_cv.predict(X_test)
print('\nTarget on test data',predict_test)


Target on test data [0 0 0 ... 0 0 0]


In [140]:
accuracy_train = accuracy_score(y_train,predict_train)
print('\naccuracy_score on train dataset : ', accuracy_train)


accuracy_score on train dataset :  1.0


In [141]:
accuracy_test = accuracy_score(y_test,predict_test)
print('\naccuracy_score on test dataset : ', accuracy_test)


accuracy_score on test dataset :  0.9546165884194053


In [142]:
rfc_cv_cr=(metrics.classification_report(y_test,predict_test))
print(rfc_cv_cr)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1220
           1       0.50      0.02      0.03        58

    accuracy                           0.95      1278
   macro avg       0.73      0.51      0.51      1278
weighted avg       0.93      0.95      0.93      1278



In [143]:
rfc_cv_cm=confusion_matrix(y_test,predict_test)
rfc_cv_cm

array([[1219,    1],
       [  57,    1]])

In [144]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
model = GradientBoostingClassifier(n_estimators=100,max_depth=5)

In [ ]:
model.fit(X_train,y_train)

GradientBoostingClassifier(max_depth=5)

In [ ]:
predict_train = model.predict(X_train)
print('\nTarget on train data',predict_train)


Target on train data [0 0 0 ... 0 0 0]


In [ ]:
predict_test = model.predict(X_test)
print('\nTarget on train data',predict_test)


Target on train data [0 0 0 ... 0 0 0]


In [ ]:
accuracy_train = accuracy_score(y_train,predict_train)
print('\naccuracy_score on train dataset : ', accuracy_train)


accuracy_score on train dataset :  0.9838204592901879


In [ ]:
accuracy_test = accuracy_score(y_test,predict_test)
print('\naccuracy_score on train dataset : ', accuracy_test)


accuracy_score on train dataset :  0.9475743348982786


In [ ]:
n_estimators = [100,140,145,150,160, 170,175,180,185];
cv = StratifiedShuffleSplit(n_splits=10, test_size=.30, random_state=15)
learning_r = [0.1,1,0.01,0.5]

In [ ]:
parameters = {'n_estimators':n_estimators,
              'learning_rate':learning_r,
              'criterion':['friedman_mse','squared_error','mse'],
              'loss':['log_loss','deviance','exponential']
              
        }

In [ ]:
grid = GridSearchCV(estimator=GradientBoostingClassifier(),
                                 param_grid=parameters,
                                 cv=cv,
                                 n_jobs = -1)

In [ ]:
grid.fit(X_train,y_train)

In [ ]:
print (grid.best_score_)
print (grid.best_params_)
print (grid.best_estimator_)

0.9504347826086956
{'criterion': 'friedman_mse', 'learning_rate': 0.01, 'loss': 'exponential', 'n_estimators': 100}
GradientBoostingClassifier(learning_rate=0.01, loss='exponential')


In [ ]:
gb_cv = GradientBoostingClassifier(learning_rate=0.01, loss='exponential',n_estimators= 100)

In [ ]:
gb_cv.fit(X_train,y_train)

GradientBoostingClassifier(learning_rate=0.01, loss='exponential')

In [ ]:
predict_train = model.predict(X_train)
print('\nTarget on train data',predict_train)


Target on train data [0 0 0 ... 0 0 0]


In [ ]:
predict_test = model.predict(X_test)
print('\nTarget on test data',predict_test)


Target on test data [0 0 0 ... 0 0 0]


In [ ]:
accuracy_train = accuracy_score(y_train,predict_train)
print('\naccuracy_score on train dataset : ', accuracy_train)


accuracy_score on train dataset :  0.9838204592901879


In [ ]:
accuracy_test = accuracy_score(y_test,predict_test)
print('\naccuracy_score on train dataset : ', accuracy_test)


accuracy_score on train dataset :  0.9475743348982786


In [ ]:
gb_cr=(metrics.classification_report(y_test,predict_test))
print(gb_cr)

              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1220
           1       0.20      0.05      0.08        58

    accuracy                           0.95      1278
   macro avg       0.58      0.52      0.53      1278
weighted avg       0.92      0.95      0.93      1278



In [ ]:
gb_cm=confusion_matrix(y_test,predict_test)
gb_cm

array([[1208,   12],
       [  55,    3]])

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier

In [ ]:
adaBoost = AdaBoostClassifier(base_estimator=None,
                              learning_rate=1.0,
                              n_estimators=100)

In [ ]:
adaBoost.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100)

In [ ]:
y_pred = adaBoost.predict(X_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.9546165884194053

In [ ]:
n_estimators = [100,140,145,150,160, 170,175,180,185];
cv = StratifiedShuffleSplit(n_splits=10, test_size=.30, random_state=15)

In [ ]:
learning_r = [0.1,1,0.01,0.5]

In [ ]:
parameters = {'n_estimators':n_estimators,
              'learning_rate':learning_r,
              'algorithm':['SAMME','SAMME.R']}

In [ ]:
grid = GridSearchCV(AdaBoostClassifier(base_estimator=RandomForestClassifier()), ## If None, then the base estimator is a decision tree.
                                 param_grid=parameters,
                                 cv=cv,
                                 n_jobs = -1)

In [ ]:
grid.fit(X_train,y_train) 

GridSearchCV(cv=StratifiedShuffleSplit(n_splits=10, random_state=15, test_size=0.3,
            train_size=None),
             estimator=AdaBoostClassifier(base_estimator=RandomForestClassifier()),
             n_jobs=-1,
             param_grid={'algorithm': ['SAMME', 'SAMME.R'],
                         'learning_rate': [0.1, 1, 0.01, 0.5],
                         'n_estimators': [100, 140, 145, 150, 160, 170, 175,
                                          180, 185]})

In [ ]:
print (grid.best_score_)
print (grid.best_params_)
print (grid.best_estimator_)

0.9492173913043478
{'algorithm': 'SAMME.R', 'learning_rate': 1, 'n_estimators': 150}
AdaBoostClassifier(base_estimator=RandomForestClassifier(), learning_rate=1,
                   n_estimators=150)


In [ ]:
adaBoost_grid = grid.best_estimator_

In [ ]:
adaBoost_grid.score(X_train,y_train)

1.0

In [ ]:
abc=AdaBoostClassifier(base_estimator=RandomForestClassifier(), learning_rate=1,
                   n_estimators=150)

In [ ]:
abc.fit(X_train,y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier(), learning_rate=1,
                   n_estimators=150)

In [ ]:
predict_train = abc.predict(X_train)
print('\nTarget on train data',predict_train)


Target on train data [0 0 0 ... 0 0 0]


In [ ]:
predict_test = abc.predict(X_test)
print('\nTarget on test data',predict_test)


Target on test data [0 0 0 ... 0 0 0]


In [ ]:
accuracy_train = accuracy_score(y_train,predict_train)
print('\naccuracy_score on train dataset : ', accuracy_train)


accuracy_score on train dataset :  1.0


In [ ]:
accuracy_test = accuracy_score(y_test,predict_test)
print('\naccuracy_score on test dataset : ', accuracy_test)


accuracy_score on test dataset :  0.9553990610328639


In [ ]:
abc_cr=(metrics.classification_report(y_test,predict_test))
print(abc_cr)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1220
           1       0.67      0.03      0.07        58

    accuracy                           0.96      1278
   macro avg       0.81      0.52      0.52      1278
weighted avg       0.94      0.96      0.94      1278



In [ ]:
print(score)

0.9530516431924883


In [ ]:
print(metrics.classification_report(y_test,predict_test))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1220
           1       0.67      0.03      0.07        58

    accuracy                           0.96      1278
   macro avg       0.81      0.52      0.52      1278
weighted avg       0.94      0.96      0.94      1278



In [ ]:
abc_cm=confusion_matrix(y_test,predict_test)
abc_cm

array([[1219,    1],
       [  56,    2]])

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb = XGBClassifier(n_estimators=100,booster='gbtree')

In [ ]:
xgb.fit(X_train,y_train)

XGBClassifier()

In [ ]:
predict_train = xgb.predict(X_train)
print('\nTarget on train data',predict_train)


Target on train data [0 0 0 ... 0 0 0]


In [ ]:
predict_test = xgb.predict(X_test)
print('\nTarget on test data',predict_test)


Target on test data [0 0 0 ... 0 0 0]


In [ ]:
accuracy_test = accuracy_score(y_test,predict_test)
print('\naccuracy_score on test dataset : ', accuracy_test)


accuracy_score on test dataset :  0.9546165884194053


In [ ]:
accuracy_train = accuracy_score(y_train,predict_train)
print('\naccuracy_score on train dataset : ', accuracy_train)


accuracy_score on train dataset :  0.9509394572025052


In [ ]:
xgb_cr=(metrics.classification_report(y_test,predict_test))
print(xgb_cr)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1220
           1       0.50      0.02      0.03        58

    accuracy                           0.95      1278
   macro avg       0.73      0.51      0.51      1278
weighted avg       0.93      0.95      0.93      1278



In [ ]:
xgb_cm=confusion_matrix(y_test,predict_test)
xgb_cm

array([[1219,    1],
       [  57,    1]])

In [ ]:
learning_r = [0.1,1,0.01,0.5]

In [ ]:
parameters = {'n_estimators':n_estimators,
              'learning_rate':learning_r,
              'booster':['gbtree','dart'],
              'min_split_loss':[0.1,0,0.5,1,1.5],}
           

In [ ]:
grid = GridSearchCV(XGBClassifier(base_estimator=RandomForestClassifier()), ## If None, then the base estimator is a decision tree.
                                 param_grid=parameters,
                                 cv=cv,
                                 n_jobs = -1)

In [ ]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedShuffleSplit(n_splits=10, random_state=15, test_size=0.3,
            train_size=None),
             estimator=XGBClassifier(base_estimator=RandomForestClassifier()),
             n_jobs=-1,
             param_grid={'booster': ['gbtree', 'dart'],
                         'learning_rate': [0.1, 1, 0.01, 0.5],
                         'min_split_loss': [0.1, 0, 0.5, 1, 1.5],
                         'n_estimators': [100, 140, 145, 150, 160, 170, 175,
                                          180, 185]})

In [ ]:
print (grid.best_score_)
print (grid.best_params_)
print (grid.best_estimator_)

0.9502608695652175
{'booster': 'gbtree', 'learning_rate': 0.01, 'min_split_loss': 1.5, 'n_estimators': 185}
XGBClassifier(base_estimator=RandomForestClassifier(), learning_rate=0.01,
              min_split_loss=1.5, n_estimators=185)


In [ ]:
xg_cv=XGBClassifier(base_estimator=RandomForestClassifier(), learning_rate=0.01,
              min_split_loss=1.5, n_estimators=185)

In [ ]:
xg_cv.fit(X_train,y_train)

XGBClassifier(base_estimator=RandomForestClassifier(), learning_rate=0.01,
              min_split_loss=1.5, n_estimators=185)

In [ ]:
predict_train = xg_cv.predict(X_train)
print('\nTarget on train data',predict_train)


Target on train data [0 0 0 ... 0 0 0]


In [ ]:
predict_test = xgb.predict(X_test)
print('\nTarget on test data',predict_test)


Target on test data [0 0 0 ... 0 0 0]


In [ ]:
accuracy_test = accuracy_score(y_test,predict_test)
print('\naccuracy_score on test dataset : ', accuracy_test)


accuracy_score on test dataset :  0.9546165884194053


In [ ]:
accuracy_train = accuracy_score(y_train,predict_train)
print('\naccuracy_score on test dataset : ', accuracy_train)


accuracy_score on test dataset :  0.9501565762004175


In [ ]:
xgcv_cr=(metrics.classification_report(y_test,predict_test))
print(xgcv_cr)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1220
           1       0.50      0.02      0.03        58

    accuracy                           0.95      1278
   macro avg       0.73      0.51      0.51      1278
weighted avg       0.93      0.95      0.93      1278



In [ ]:
xgcv_cm=confusion_matrix(y_test,predict_test)
xgcv_cm

array([[1219,    1],
       [  57,    1]])